import { useEffect, useState } from 'react'
import { AlertCircle, CheckCircle2, History, LoaderCircle, PencilLine, Save, Search, ShieldAlert } from 'lucide-react'
import { AssetPoolDraft, AssetPoolMember, LegacyInstrumentMember, SecurityCatalogue, SecurityCatalogueMember, SecurityRecord, fetchAssetPoolDraftHistory, fetchAssetPoolDrafts, fetchSecurityCatalogue, saveAssetPoolDraft } from '../api'
import { backendFieldErrors, FieldError, focusFirstError, labelledField, RequiredMark } from './FormValidation'

type Form = { name: string; purpose: string; selected: Record<string, AssetPoolMember> }
const blank: Form = { name: '', purpose: '', selected: {} }
const isCatalogueMember = (member: AssetPoolMember): member is SecurityCatalogueMember => 'member_type' in member
const memberKey = (member: AssetPoolMember) => isCatalogueMember(member) ? `catalogue:${member.catalog_id}` : `legacy:${member.instrument_draft_id}`
const catalogMember = (record: SecurityRecord): SecurityCatalogueMember | null => record.source_checksum ? { member_type: 'security_catalogue_v1', catalog_id: record.catalog_id, source_checksum: record.source_checksum, record_snapshot: record } : null
const requestMember = (member: AssetPoolMember) => isCatalogueMember(member) ? { member_type: member.member_type, catalog_id: member.catalog_id, source_checksum: member.source_checksum } : { instrument_draft_id: member.instrument_draft_id, instrument_version: member.instrument_version }
const memberLabel = (member: AssetPoolMember) => !isCatalogueMember(member) ? `历史手工档案 · ${member.instrument_draft_id.slice(0, 8)} · v${member.instrument_version}` : `${member.record_snapshot.symbol} · ${member.record_snapshot.name || '来源未提供名称'} · ${member.record_snapshot.status === 'delisted' ? '历史退市' : '主表标记活跃'}`

export function AssetPoolWorkspace({ onNavigate }: { onNavigate?: (page: string) => void }) {
  const [pools, setPools] = useState<AssetPoolDraft[] | null>(null); const [catalogue, setCatalogue] = useState<SecurityCatalogue | null>(null); const [editing, setEditing] = useState<AssetPoolDraft | null>(null); const [history, setHistory] = useState<AssetPoolDraft[] | null>(null)
  const [form, setForm] = useState<Form>(blank); const [query, setQuery] = useState(''); const [appliedQuery, setAppliedQuery] = useState(''); const [error, setError] = useState(''); const [savedMessage, setSavedMessage] = useState(''); const [saving, setSaving] = useState(false); const [refresh, setRefresh] = useState(0); const [formErrors, setFormErrors] = useState<Record<string, string>>({})
  const fieldIds = { name: 'asset-pool-name', purpose: 'asset-pool-purpose', instruments: 'asset-pool-instruments' }
  useEffect(() => { const c = new AbortController(); setError(''); setCatalogue(null); Promise.all([fetchAssetPoolDrafts(c.signal), fetchSecurityCatalogue(appliedQuery, c.signal)]).then(([nextPools, nextCatalogue]) => { setPools(nextPools); setCatalogue(nextCatalogue) }).catch(reason => { if (!c.signal.aborted) setError(reason instanceof Error ? reason.message : '无法读取研究股票池') }); return () => c.abort() }, [refresh, appliedQuery])
  const edit = async (pool: AssetPoolDraft) => { setFormErrors({}); setSavedMessage(''); setEditing(pool); setForm({ name: pool.name, purpose: pool.purpose, selected: Object.fromEntries(pool.instruments.map(member => [memberKey(member), member])) }); setError(''); try { setHistory(await fetchAssetPoolDraftHistory(pool.id, new AbortController().signal)) } catch (reason) { setError(reason instanceof Error ? reason.message : '无法读取历史') } }
  const newPool = () => { setEditing(null); setHistory(null); setForm(blank); setFormErrors({}); setSavedMessage(''); setError('') }
  const toggle = (member: AssetPoolMember, enabled: boolean) => setForm(current => { const selected = { ...current.selected }; const key = memberKey(member); if (enabled) selected[key] = member; else delete selected[key]; return { ...current, selected } })
  const search = () => { const next = query.trim(); if (next === appliedQuery) setRefresh(value => value + 1); else setAppliedQuery(next) }
  const save = async () => {
    if (saving) return; setError(''); setSavedMessage(''); const errors: Record<string, string> = {}
    if (!form.name.trim() || form.name.trim().length > 120) errors.name = '股票池名称为 1–120 个字符。'
    if (!form.purpose.trim() || form.purpose.trim().length > 1000) errors.purpose = '研究用途为 1–1000 个字符。'
    const members = Object.values(form.selected); if (members.length < 1 || members.length > 200) errors.instruments = '请选择 1–200 个自动证券档案或保留的历史手工档案。'
    if (Object.keys(errors).length) { setFormErrors(errors); focusFirstError(errors, fieldIds); return }
    setFormErrors({}); setSaving(true)
    try { const result = await saveAssetPoolDraft({ name: form.name, purpose: form.purpose, instruments: members.map(requestMember) }, editing?.id); setEditing(result); setForm({ name: result.name, purpose: result.purpose, selected: Object.fromEntries(result.instruments.map(member => [memberKey(member), member])) }); setHistory(await fetchAssetPoolDraftHistory(result.id, new AbortController().signal)); setSavedMessage(`已保存 ${result.name} v${result.version}；策略将固定引用此版本。`); setRefresh(value => value + 1) } catch (reason) { const mapped = backendFieldErrors(reason, Object.keys(fieldIds)); if (Object.keys(mapped).length) { setFormErrors(mapped); focusFirstError(mapped, fieldIds) } else setError(reason instanceof Error ? reason.message : '保存失败') } finally { setSaving(false) }
  }
  const selected = Object.values(form.selected); const preservedLegacy = selected.filter(member => !isCatalogueMember(member)) as LegacyInstrumentMember[]
  if (error && (!pools || !catalogue)) return <section className="empty-state wide"><AlertCircle size={24}/><strong>研究股票池暂不可用</strong><p>{error}</p><button className="detail-action" onClick={() => setRefresh(value => value + 1)}>重新读取</button></section>
  if (!pools || !catalogue) return <section className="empty-state wide"><LoaderCircle size={24} className="animate-spin"/><strong>正在读取研究股票池</strong><p>仅加载固定股票池版本和自动证券目录；不会读取行情或计算研究结果。</p></section>
  return <div className="universe-workspace"><section className="page-heading"><div><p className="eyebrow">研究工具 · 版本化引用</p><h1>研究股票池</h1><p>搜索并勾选自动证券档案，保存固定名单版本供策略引用。目录资料不会自动获得研究或回测资格。</p></div><span className="static-boundary">研究配置 · 不可执行</span></section>
    {error && <div className="strategy-error"><AlertCircle size={17}/>{error}</div>}{savedMessage && <div className="asset-pool-success" role="status"><CheckCircle2 size={17}/>{savedMessage}</div>}
    <section className="strategy-boundary"><ShieldAlert size={18}/><div><strong>目录引用不等于合格研究资产</strong><p>每个新成员固定来源导入版本与当时的身份记录快照。目录身份、行情归属、交易日历和规则均仍待核验；测试记录不可引用，改名、代码复用和未知身份不会自动取得研究资格。</p></div></section>
    <div className="universe-grid"><aside className="universe-drafts"><header><strong>我的研究股票池</strong><button type="button" className="detail-action" onClick={newPool}>新建</button></header>{pools.length ? pools.map(pool => <button key={pool.id} className={editing?.id === pool.id ? 'is-active' : ''} onClick={() => edit(pool)}><span><strong>{pool.name}</strong><small>{pool.instrument_count} 项 · v{pool.version}</small></span><PencilLine size={14}/></button>) : <p>尚无研究股票池。直接搜索并选择自动证券档案，无需创建技术档案。</p>}</aside>
      <section className="universe-editor"><header><div><h2>{editing ? `编辑 ${editing.name}` : '新建研究股票池'}</h2><p>保存会创建新版本；策略保存后继续引用所选股票池版本，不会随名单更新而改写。</p></div><span>v{editing?.version || 1}</span></header>
        <div className="universe-form"><label>股票池名称 <RequiredMark /><input {...labelledField(fieldIds.name, formErrors.name)} maxLength={120} value={form.name} onChange={e => { setFormErrors(v => ({ ...v, name: '' })); setForm(current => ({ ...current, name: e.target.value })) }}/><FieldError id={`${fieldIds.name}-error`} message={formErrors.name}/></label><label>研究用途 <RequiredMark /><textarea {...labelledField(fieldIds.purpose, formErrors.purpose)} maxLength={1000} value={form.purpose} onChange={e => { setFormErrors(v => ({ ...v, purpose: '' })); setForm(current => ({ ...current, purpose: e.target.value })) }} placeholder="例如：历史动量研究候选名单；不代表已验证数据覆盖。"/><FieldError id={`${fieldIds.purpose}-error`} message={formErrors.purpose}/></label></div>
        <section id={fieldIds.instruments} tabIndex={-1} className="asset-pool-members" aria-invalid={Boolean(formErrors.instruments)} aria-describedby={formErrors.instruments ? `${fieldIds.instruments}-error` : undefined}><strong>自动证券档案 <RequiredMark /></strong><div className="asset-pool-search"><Search size={15}/><input value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') search() }} maxLength={120} placeholder="代码或名称，例如 TSLA" aria-label="搜索自动证券档案"/><button type="button" className="detail-action" onClick={search}>搜索</button></div>{selected.length > 0 && <div className="asset-pool-selected"><strong>已选证券 {selected.length}/200</strong>{selected.map(member => <div key={memberKey(member)}><span><b>{memberLabel(member)}</b><small>{isCatalogueMember(member) ? `来源版本 ${member.source_checksum.slice(0, 12)}… · 身份待核验` : '旧版手工档案引用'}</small></span><button type="button" className="detail-action" onClick={() => toggle(member, false)}>移除</button></div>)}</div>}<p className="asset-pool-member-note">{catalogue.total_records ? `显示 ${catalogue.total} 条匹配；测试隔离记录不会显示或保存。` : '目录尚未导入，暂时不能创建自动证券引用。'}</p>{catalogue.items.map(record => { const member = catalogMember(record); const checked = member ? memberKey(member) in form.selected : false; return <label key={record.catalog_id} className="asset-pool-catalogue-member"><input type="checkbox" checked={checked} disabled={!member} onChange={event => { setFormErrors(v => ({ ...v, instruments: '' })); if (member) toggle(member, event.target.checked) }}/><span><b>{record.symbol} · {record.name || '来源未提供名称'}</b><small>{record.exchange || '来源未提供市场'} · {record.asset_type.toUpperCase()} · 来源快照 {record.source_as_of || '日期未知'}</small>{record.status === 'delisted' && <p>历史退市：可配置为历史研究名单，但不表示退市回报、公司行为或正式回测数据完整。</p>}{!member && <p>该目录记录缺少可固定的来源版本，不能保存为股票池成员。</p>}</span></label>})}{!catalogue.items.length && <p>{catalogue.total_records ? '未找到匹配证券，请换一个代码或名称。' : '证券目录尚未导入。请由维护流程导入来源主表；不需要手工创建证券档案。'} <button type="button" className="detail-action" onClick={() => onNavigate?.('instruments')}>查看证券档案</button></p>}{preservedLegacy.length > 0 && <><strong>保留的历史手工档案</strong><p className="asset-pool-member-note">为保持旧股票池与策略版本可追溯，未自动迁移为目录记录。取消勾选后，该成员只会从下一版股票池移除。</p>{preservedLegacy.map(member => <label key={memberKey(member)}><input type="checkbox" checked onChange={event => { setFormErrors(v => ({ ...v, instruments: '' })); toggle(member, event.target.checked) }}/><span><b>{memberLabel(member)}</b><small>兼容旧版引用；不是自动证券档案。</small></span></label>)}</>}<FieldError id={`${fieldIds.instruments}-error`} message={formErrors.instruments}/></section>
        <button type="button" className="strategy-save" disabled={saving} onClick={save}><Save size={15}/>{saving ? '保存中…' : editing ? '保存股票池新版本' : '创建研究股票池'}</button>
      </section></div>
    {history && <section className="strategy-history"><header><div><History size={17}/><strong>{editing?.name} 的股票池历史</strong></div><span>{history.length} 个版本</span></header>{history.map(item => <div key={item.id}><strong>v{item.version}</strong><span>{item.instrument_count} 项（自动目录 {item.catalogue_member_count ?? 0}，旧档案 {item.legacy_instrument_count ?? 0}）· {item.purpose}</span><time>{new Date(item.created_at).toLocaleString()}</time></div>)}</section>}
  </div>
}
