import { AlertCircle, FlaskConical, LoaderCircle, Play, RefreshCw } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { idempotencyKey } from '../idempotency'
import { Factor, FactorResearchAvailability, Job, fetchFactorCatalogue, fetchFactorResearchAvailability, fetchFactorResult, fetchJob, submitFactorResearch } from '../api'

export function FactorResearch() {
  const [gate, setGate] = useState<FactorResearchAvailability | null>(null); const [factors, setFactors] = useState<Factor[]>([])
  const [factorId, setFactorId] = useState(''); const [snapshot, setSnapshot] = useState(''); const [job, setJob] = useState<Job | null>(null); const [result, setResult] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState('')
  const runnable = useMemo(() => factors.filter(item => item.runnable), [factors])
  const load = () => { const controller = new AbortController(); setError(''); Promise.all([fetchFactorResearchAvailability(controller.signal), fetchFactorCatalogue(controller.signal)]).then(([g, c]) => { setGate(g); setFactors(c.items); setSnapshot(g.snapshots[0] || ''); setFactorId(c.items.find(item => item.runnable)?.id || '') }).catch(reason => setError(reason instanceof Error ? reason.message : '读取失败')); return () => controller.abort() }
  useEffect(load, [])
  useEffect(() => { if (!job || ['succeeded', 'failed', 'cancelled'].includes(job.status)) return; const timer = window.setInterval(() => fetchJob(job.id, new AbortController().signal).then(setJob).catch(reason => setError(reason.message)), 1500); return () => window.clearInterval(timer) }, [job])
  useEffect(() => { if (job?.status !== 'succeeded') return; fetchFactorResult(job.id, new AbortController().signal).then(setResult).catch(reason => setError(reason.message)) }, [job?.status])
  const submit = async () => { if (!gate?.available || !factorId || !snapshot) return; setError(''); setResult(null); try { const key = idempotencyKey('factor'); setJob(await submitFactorResearch({ kind: 'research', operation: 'factor_evaluation', strategy: { template: 'single_factor_evaluation-v1' }, parameters: { factor_id: factorId, symbols: [], holding_period: 5, quantiles: 5, min_cross_section: 5 }, data_snapshot: snapshot, code_version: 'ui-submission-v1' }, key)) } catch (reason) { setError(reason instanceof Error ? reason.message : '提交失败') } }
  const summary = result?.result as { metrics?: Record<string, unknown>; coverage?: Array<{ 指标: string; 数值: unknown }>; diagnostics?: { limitations?: string[] } } | undefined
  return <div className="factor-research"><section className="page-heading"><div><p className="eyebrow">研究实验室 · 异步因子检验</p><h1>因子研究</h1><p>仅使用服务器登记的固定快照。IC、分组收益和换手是研究统计，不是可执行策略收益。</p></div></section>
    {error && <section className="empty-state wide"><AlertCircle size={24}/><strong>无法继续研究</strong><p>{error}</p><button className="detail-action" onClick={load}><RefreshCw size={15}/>重新读取</button></section>}
    {!gate && !error ? <section className="empty-state wide"><LoaderCircle className="animate-spin" size={24}/><strong>正在读取研究门禁</strong></section> : gate && !gate.available ? <section className="empty-state wide"><AlertCircle size={24}/><strong>研究计算已阻断</strong><p>{gate.message}</p><p>不会用 P1-04 代表性事件快照、演示数据或不完整退市回报代替合格资产池。</p></section> : gate && <><section className="research-form"><label>固定数据快照<select value={snapshot} onChange={e => setSnapshot(e.target.value)}>{gate.snapshots.map(item => <option key={item}>{item}</option>)}</select></label><label>可计算因子<select value={factorId} onChange={e => setFactorId(e.target.value)}>{runnable.map(item => <option key={item.id} value={item.id}>{item.name} · {item.id}</option>)}</select></label><div><strong>输入边界</strong><p>5 个持有期可用 bar、5 分组、至少 5 个截面；固定公式与快照版本将写入产物。</p></div><button type="button" className="research-submit" onClick={submit} disabled={!factorId || !snapshot || job?.status === 'queued' || job?.status === 'running'}><Play size={15}/>提交检验</button></section>{job && <section className="research-status"><FlaskConical size={19}/><div><strong>任务 {job.status === 'queued' ? '排队中' : job.status === 'running' ? '运行中' : job.status === 'succeeded' ? '已发布' : '失败'}</strong><p>{job.failure?.message || `快照 ${job.data_snapshot} · ${job.operation}`}</p></div></section>}{summary && <section className="research-results"><h2>已发布研究结果</h2><p>结果包含缺失率/覆盖、日度 IC（RankIC）和分组换手；未扣除公司行动、费用、滑点或退市结果。</p><div className="metric-grid">{Object.entries(summary.metrics || {}).map(([key, value]) => <article className="metric-card" key={key}><span>{key}</span><strong>{value == null ? '不可用' : Number(value).toFixed(4)}</strong></article>)}</div><div className="coverage-list">{(summary.coverage || []).map(row => <span key={row.指标}>{row.指标}：{String(row.数值)}</span>)}</div><ul>{summary.diagnostics?.limitations?.map(item => <li key={item}>{item}</li>)}</ul></section>}</>}</div>
}
