import { useEffect, useMemo, useState } from 'react'
import { AlertCircle, CheckCircle2, History, LoaderCircle, PencilLine, Save, ShieldAlert } from 'lucide-react'
import { StrategyDraft, StrategyTemplate, fetchStrategyDraftHistory, fetchStrategyDrafts, fetchStrategyTemplates, saveStrategyDraft } from '../api'

const initial = (template: StrategyTemplate): Record<string, string> => {
  const fallback: Record<string, string> = { symbol: 'SPY', start_date: '2020-01-02', fast_window: '20', slow_window: '60' }
  return Object.fromEntries(Object.entries(template.parameters).map(([key, item]) => [key, item.default || fallback[key] || '']))
}

export function StrategyWorkspace() {
  const [templates, setTemplates] = useState<StrategyTemplate[] | null>(null); const [drafts, setDrafts] = useState<StrategyDraft[] | null>(null)
  const [selected, setSelected] = useState<StrategyTemplate | null>(null); const [editing, setEditing] = useState<StrategyDraft | null>(null)
  const [name, setName] = useState(''); const [parameters, setParameters] = useState<Record<string, string>>({}); const [history, setHistory] = useState<StrategyDraft[] | null>(null)
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [refresh, setRefresh] = useState(0)
  useEffect(() => { const controller = new AbortController(); setError(''); Promise.all([fetchStrategyTemplates(controller.signal), fetchStrategyDrafts(controller.signal)]).then(([items, saved]) => { setTemplates(items); setDrafts(saved); const active = items[0]; setSelected(active); if (!editing) { setName(active?.name || ''); setParameters(active ? initial(active) : {}) } }).catch(reason => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : '无法读取策略工作台') }); return () => controller.abort() }, [refresh])
  const selectTemplate = (template: StrategyTemplate) => { setSelected(template); setEditing(null); setHistory(null); setName(template.name); setParameters(initial(template)); setError('') }
  const edit = async (draft: StrategyDraft) => { const template = templates?.find(item => item.id === draft.template) || null; setSelected(template); setEditing(draft); setName(draft.name); setParameters(Object.fromEntries(Object.entries(draft.parameters).map(([key, value]) => [key, String(value)]))); setError(''); try { setHistory(await fetchStrategyDraftHistory(draft.id, new AbortController().signal)) } catch (reason) { setError(reason instanceof Error ? reason.message : '无法读取历史') } }
  const save = async () => { if (!selected || saving) return; setSaving(true); setError(''); try { const result = await saveStrategyDraft({ name, template: selected.id, parameters }, editing?.id); setEditing(result); setHistory(await fetchStrategyDraftHistory(result.id, new AbortController().signal)); setRefresh(value => value + 1) } catch (reason) { setError(reason instanceof Error ? reason.message : '保存失败') } finally { setSaving(false) } }
  const templateTitle = useMemo(() => selected ? `${selected.name} · ${selected.version}` : '读取中', [selected])
  if (error && !templates) return <section className="empty-state wide"><AlertCircle size={24}/><strong>策略工作台暂不可用</strong><p>{error}</p><button className="detail-action" onClick={() => setRefresh(value => value + 1)}>重新读取</button></section>
  if (!templates || !drafts || !selected) return <section className="empty-state wide"><LoaderCircle size={24} className="animate-spin"/><strong>正在读取策略模板与草稿</strong><p>仅读取固定模板和 SQLite 草稿记录，不会读取行情或运行策略。</p></section>
  return <div className="strategy-workspace"><section className="page-heading"><div><p className="eyebrow">策略中心 · 版本化定义</p><h1>策略工作台</h1><p>这里保存的是可审核的策略草稿，不是已验证的运行策略；保存不会读取行情、创建回测或连接账户。</p></div><span className="static-boundary">草稿 · 不可执行</span></section>
    {error && <div className="strategy-error"><AlertCircle size={17}/>{error}</div>}
    <section className="strategy-boundary"><ShieldAlert size={18}/><div><strong>运行能力尚未开放</strong><p>草稿只能作为后续已验收回测或模拟盘的唯一策略输入。当前不会生成信号、收益、订单或账户操作。</p></div></section>
    <div className="strategy-grid"><aside className="strategy-library"><header><strong>固定模板</strong><span>{templates.length} 个</span></header>{templates.map(item => <button key={item.id} className={selected.id === item.id && !editing ? 'is-active' : ''} onClick={() => selectTemplate(item)}><strong>{item.name}</strong><small>{item.version}</small><span>{item.description}</span></button>)}</aside>
      <section className="strategy-editor"><header><div><h2>{editing ? `编辑草稿 · v${editing.version + 1}` : '新建草稿'}</h2><p>{templateTitle}。模板版本由服务端固定，不能手动修改。</p></div>{editing && <button className="detail-action" onClick={() => selected && selectTemplate(selected)}>新建副本</button>}</header><label>草稿名称<input value={name} maxLength={120} onChange={event => setName(event.target.value)} placeholder="例如：SPY 趋势观察"/></label><div className="strategy-form">{Object.entries(selected.parameters).map(([key, schema]) => <label key={key}>{key}{schema.required && <em>必填</em>}<input value={parameters[key] ?? ''} inputMode={schema.type === 'integer' || schema.type === 'decimal' ? 'decimal' : undefined} onChange={event => setParameters(value => ({ ...value, [key]: event.target.value }))}/><small>{schema.description}{schema.range ? ` · 范围 ${schema.range}` : ''}</small></label>)}</div><button className="strategy-save" disabled={saving} onClick={save}>{saving ? <LoaderCircle className="animate-spin" size={16}/> : <Save size={16}/>}{editing ? '保存为新版本' : '保存草稿'}</button></section>
      <aside className="strategy-drafts"><header><strong>我的草稿</strong><span>{drafts.length} 项</span></header>{drafts.length ? drafts.map(item => <button key={item.id} className={editing?.id === item.id ? 'is-active' : ''} onClick={() => edit(item)}><span><strong>{item.name}</strong><small>{item.template_version} · v{item.version}</small></span><PencilLine size={14}/></button>) : <div className="strategy-empty"><CheckCircle2 size={18}/><strong>还没有草稿</strong><p>选择固定模板并保存即可创建第一版。</p></div>}</aside>
    </div>
    {history && <section className="strategy-history"><header><div><History size={17}/><strong>{editing?.name} 的草稿历史</strong></div><span>{history.length} 个版本</span></header>{history.map(item => <div key={item.id}><strong>v{item.version}</strong><span>{item.template_version} · {Object.entries(item.parameters).map(([key, value]) => `${key}=${String(value)}`).join(' · ')}</span><time>{new Date(item.created_at).toLocaleString()}</time></div>)}</section>}
  </div>
}
