import { useEffect, useState } from 'react'
import { AlertCircle, History, LoaderCircle, PencilLine, Save, ShieldAlert } from 'lucide-react'
import { InstrumentDraft, fetchInstrumentDraftHistory, fetchInstrumentDrafts, saveInstrumentDraft } from '../api'
import { backendFieldErrors, FieldError, focusFirstError, labelledField, RequiredMark } from './FormValidation'
import { isIsoDate } from '../inputValidation'

type Form = Record<string, string>
const blank: Form = { name: '示例美股定义', product: 'US_EQUITY', venue: 'NYSE', identity_key: 'US-EXAMPLE-001', venue_symbol: 'EXM', base_currency: 'USD', quote_currency: 'USD', settlement_currency: 'USD', expiry: '', timezone: 'America/New_York', calendar_id: 'US-EQUITY-DRAFT', valid_from: '2024-01-01', rule_version: 'draft-v1', quantity_unit: 'share', multiplier: '1', tick_size: '0.01', lot_size: '1', min_notional: '' }
const derivatives = new Set(['CN_FUTURE', 'GLOBAL_FUTURE', 'CRYPTO_PERPETUAL', 'CRYPTO_DELIVERY'])
const expiryRequired = new Set(['CN_FUTURE', 'GLOBAL_FUTURE', 'CRYPTO_DELIVERY'])
const crypto = new Set(['CRYPTO_SPOT', 'CRYPTO_PERPETUAL', 'CRYPTO_DELIVERY'])
const products = [['US_EQUITY', '美股'], ['CRYPTO_SPOT', '加密现货'], ['CRYPTO_PERPETUAL', '加密永续'], ['CRYPTO_DELIVERY', '加密交割'], ['CN_FUTURE', '国内期货'], ['GLOBAL_FUTURE', '海外期货']]
const field = (form: Form, key: string) => form[key] || ''

function formToInstrument(form: Form): Record<string, unknown> {
  const product = form.product
  const instrument: Record<string, unknown> = { instrument_id: `${form.venue}:${form.identity_key}`, identity_key: form.identity_key, asset: product === 'US_EQUITY' ? 'equity' : (crypto.has(product) ? 'crypto' : 'future'), product, venue: form.venue, venue_symbol: form.venue_symbol, timezone: form.timezone, calendar_id: form.calendar_id, linear: derivatives.has(product) && form.contract_model === 'linear', inverse: derivatives.has(product) && form.contract_model === 'inverse', symbol_history: [{ venue_symbol: form.venue_symbol, valid_from: form.valid_from }], rules: [{ valid_from: form.valid_from, rule_version: form.rule_version, quantity_unit: form.quantity_unit, tick_size: form.tick_size, lot_size: form.lot_size }] }
  if (crypto.has(product)) Object.assign(instrument, { base_currency: form.base_currency, quote_currency: form.quote_currency, settlement_currency: form.settlement_currency })
  if (derivatives.has(product)) Object.assign((instrument.rules as Record<string, unknown>[])[0], { multiplier: form.multiplier })
  if (expiryRequired.has(product)) instrument.expiry = form.expiry
  return instrument
}
function instrumentToForm(draft: InstrumentDraft): Form {
  const item = draft.instrument; const rule = (item.rules as Record<string, unknown>[] || [])[0] || {}; const symbol = (item.symbol_history as Record<string, unknown>[] || [])[0] || {}
  return { ...blank, name: draft.name, product: String(item.product || blank.product), venue: String(item.venue || ''), identity_key: String(item.identity_key || ''), venue_symbol: String(item.venue_symbol || ''), base_currency: String(item.base_currency || ''), quote_currency: String(item.quote_currency || ''), settlement_currency: String(item.settlement_currency || ''), expiry: String(item.expiry || ''), timezone: String(item.timezone || ''), calendar_id: String(item.calendar_id || ''), valid_from: String(symbol.valid_from || rule.valid_from || ''), rule_version: String(rule.rule_version || ''), quantity_unit: String(rule.quantity_unit || ''), multiplier: String(rule.multiplier || '1'), tick_size: String(rule.tick_size || ''), lot_size: String(rule.lot_size || '') }
}

export function InstrumentWorkspace() {
  const [drafts, setDrafts] = useState<InstrumentDraft[] | null>(null); const [editing, setEditing] = useState<InstrumentDraft | null>(null); const [history, setHistory] = useState<InstrumentDraft[] | null>(null); const [form, setForm] = useState<Form>(blank); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [refresh, setRefresh] = useState(0); const [formErrors, setFormErrors] = useState<Record<string, string>>({})
  useEffect(() => { const c = new AbortController(); setError(''); fetchInstrumentDrafts(c.signal).then(setDrafts).catch(reason => { if (!c.signal.aborted) setError(reason instanceof Error ? reason.message : '无法读取标的定义草稿') }); return () => c.abort() }, [refresh])
  const change = (key: string, value: string) => { setForm(current => ({ ...current, [key]: value })); setFormErrors(v => ({ ...v, [key]: '' })) }
  const edit = async (draft: InstrumentDraft) => { setEditing(draft); setForm(instrumentToForm(draft)); setError(''); try { setHistory(await fetchInstrumentDraftHistory(draft.id, new AbortController().signal)) } catch (reason) { setError(reason instanceof Error ? reason.message : '无法读取历史') } }
  const save = async () => { if (saving) return; setError(''); const errors: Record<string, string> = {}; const ids = Object.fromEntries(Object.keys(form).map(key => [key, `instrument-${key}`])); for (const key of ['name', 'venue', 'identity_key', 'venue_symbol', 'timezone', 'calendar_id', 'valid_from', 'rule_version', 'quantity_unit', 'tick_size', 'lot_size'] as const) if (!form[key].trim()) errors[key] = '此字段为必填项。'; if (form.name.trim().length > 120) errors.name = '定义名称为 1–120 个字符。'; if (!isIsoDate(form.valid_from)) errors.valid_from = '请输入有效的 YYYY-MM-DD 日期。'; for (const key of ['tick_size', 'lot_size'] as const) if (!/^(?:\d+(?:\.\d+)?|\.\d+)$/.test(form[key]) || Number(form[key]) <= 0) errors[key] = '请输入大于 0 的十进制数。'; if (isDerivative && (!/^(?:\d+(?:\.\d+)?|\.\d+)$/.test(form.multiplier) || Number(form.multiplier) <= 0)) errors.multiplier = '合约乘数必须为大于 0 的十进制数。'; if (expiryRequired.has(form.product) && (!isIsoDate(form.expiry))) errors.expiry = '请输入有效的到期日。'; if (isCrypto) for (const key of ['base_currency', 'quote_currency', 'settlement_currency'] as const) if (!form[key].trim()) errors[key] = '加密产品必须提供此币种。'; if (Object.keys(errors).length) { setFormErrors(errors); focusFirstError(errors, ids); return } setFormErrors({}); setSaving(true); try { const result = await saveInstrumentDraft({ name: form.name, instrument: formToInstrument(form) }, editing?.id); setEditing(result); setHistory(await fetchInstrumentDraftHistory(result.id, new AbortController().signal)); setRefresh(value => value + 1) } catch (reason) { const mapped = backendFieldErrors(reason, Object.keys(ids)); if (Object.keys(mapped).length) { setFormErrors(mapped); focusFirstError(mapped, ids) } else setError(reason instanceof Error ? reason.message : '保存失败') } finally { setSaving(false) } }
  if (error && !drafts) return <section className="empty-state wide"><AlertCircle size={24}/><strong>标的定义暂不可用</strong><p>{error}</p><button className="detail-action" onClick={() => setRefresh(value => value + 1)}>重新读取</button></section>
  if (!drafts) return <section className="empty-state wide"><LoaderCircle size={24} className="animate-spin"/><strong>正在读取配置草稿</strong><p>只读取 SQLite 草稿；不会读取行情或连接账户。</p></section>
  const isCrypto = crypto.has(form.product); const isDerivative = derivatives.has(form.product)
  const inputField = (key: string, label: string, type = 'text', hint?: string) => <label>{label} <RequiredMark/><input {...labelledField(`instrument-${key}`, formErrors[key])} type={type} inputMode={['tick_size', 'lot_size', 'multiplier'].includes(key) ? 'decimal' : undefined} value={field(form, key)} onChange={e => change(key, e.target.value)}/><FieldError id={`instrument-${key}-error`} message={formErrors[key]}/>{hint && <small>{hint}</small>}</label>
  return <div className="universe-workspace"><section className="page-heading"><div><p className="eyebrow">市场与数据 · 版本化定义</p><h1>资产与合约</h1><p>保存单个证券、交易对或期货合约的稳定身份和基础规则；不代表行情覆盖或可交易性。</p></div><span className="static-boundary">定义草稿 · 不可执行</span></section>
    {error && <div className="strategy-error" role="alert"><AlertCircle size={17}/>{error}</div>}
    <section className="strategy-boundary"><ShieldAlert size={18}/><div><strong>仅保存参考配置</strong><p>不会读取行情、声明数据覆盖、创建回测或交易任务，也不会连接外部账户。</p></div></section>
    <div className="universe-grid"><aside className="universe-drafts"><header><strong>已保存标的</strong><span>{drafts.length} 项</span></header>{drafts.length ? drafts.map(item => <button key={item.id} className={editing?.id === item.id ? 'is-active' : ''} onClick={() => edit(item)}><span><strong>{item.name}</strong><small>{String(item.instrument.product)} · v{item.version}</small></span><PencilLine size={14}/></button>) : <p>尚无标的定义。保存一个单标的或合约后，才可在研究资产池中引用它。</p>}</aside>
      <section className="universe-editor"><header><div><h2>{editing ? `编辑 ${editing.name}` : '新建标的定义'}</h2><p>每个草稿只描述一个标的或合约；更新会保留可引用的历史版本。</p></div><span>v{editing?.version || 1}</span></header><div className="universe-form">
        {inputField('name', '定义名称')}<label>市场产品 <RequiredMark/><select {...labelledField('instrument-product', formErrors.product)} value={form.product} onChange={e => { setFormErrors({}); change('product', e.target.value) }}>{products.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><FieldError id="instrument-product-error" message={formErrors.product}/></label>
        {inputField('venue', '市场 / venue')}{inputField('identity_key', '稳定身份键', 'text', '不能使用 ticker')}
        {inputField('venue_symbol', '当前交易代码')}{inputField('timezone', '市场时区')}
        {inputField('calendar_id', '日历标识')}{inputField('valid_from', '规则生效日', 'date')}
        {isCrypto && <>{inputField('base_currency', '基础币种')}{inputField('quote_currency', '报价币种')}{inputField('settlement_currency', '结算币种')}</>}
        {isDerivative && <><label>合约模型 <RequiredMark/><select {...labelledField('instrument-contract_model', formErrors.contract_model)} value={field(form, 'contract_model') || 'linear'} onChange={e => change('contract_model', e.target.value)}><option value="linear">线性</option><option value="inverse">反向</option></select><FieldError id="instrument-contract_model-error" message={formErrors.contract_model}/></label>{inputField('multiplier', '合约乘数')}</>}
        {expiryRequired.has(form.product) && inputField('expiry', '到期日', 'date')}
        {inputField('rule_version', '规则版本')}{inputField('quantity_unit', '数量单位')}{inputField('tick_size', '最小变动价位')}{inputField('lot_size', '最小下单单位')}
      </div><button className="strategy-save" disabled={saving} onClick={save}><Save size={15}/>{saving ? '保存中…' : editing ? '保存新版本' : '创建标的定义'}</button></section></div>
    {history && <section className="strategy-history"><header><div><History size={17}/><strong>{editing?.name} 的定义历史</strong></div><span>{history.length} 个版本</span></header>{history.map(item => <div key={item.id}><strong>v{item.version}</strong><span>{String(item.instrument.product)} · {String(item.instrument.venue_symbol)}</span><time>{new Date(item.created_at).toLocaleString()}</time></div>)}</section>}
  </div>
}
