import { useEffect, useMemo, useState } from 'react'
import { AlertCircle, History, LoaderCircle, PencilLine, Plus, Save, ShieldAlert, Trash2 } from 'lucide-react'
import { AssetPoolDraft, Factor, VisualSignalRule, VisualStrategyDefinition, VisualStrategyDraft, fetchAssetPoolDrafts, fetchFactorCatalogue, fetchVisualStrategyDraftHistory, fetchVisualStrategyDrafts, saveVisualStrategyDraft } from '../api'

type Form = { name: string; poolId: string; poolVersion: number; rules: VisualSignalRule[]; combination: 'all' | 'any'; frequency: 'daily' | 'weekly' | 'monthly'; mode: 'equal_weight' | 'fixed_weight'; targetWeight: string; maxPositionWeight: string; maxHoldings: string }
const blank = (factor = ''): Form => ({ name: '', poolId: '', poolVersion: 0, rules: factor ? [{ factor_id: factor, operator: 'gt', threshold: 0, direction: 'long' }] : [], combination: 'all', frequency: 'monthly', mode: 'equal_weight', targetWeight: '0.1', maxPositionWeight: '0.1', maxHoldings: '20' })
const fromDraft = (draft: VisualStrategyDraft): Form => { const d = draft.definition; return { name: draft.name, poolId: d.asset_pool.asset_pool_draft_id, poolVersion: d.asset_pool.asset_pool_version, rules: d.signal_rules, combination: d.combination, frequency: d.rebalance_frequency, mode: d.allocation.mode, targetWeight: String(d.allocation.target_weight ?? 0.1), maxPositionWeight: String(d.constraints.max_position_weight), maxHoldings: String(d.constraints.max_holdings) } }

export function VisualStrategyWorkspace() {
  const [drafts, setDrafts] = useState<VisualStrategyDraft[] | null>(null); const [pools, setPools] = useState<AssetPoolDraft[] | null>(null); const [factors, setFactors] = useState<Factor[] | null>(null)
  const [editing, setEditing] = useState<VisualStrategyDraft | null>(null); const [history, setHistory] = useState<VisualStrategyDraft[] | null>(null); const [form, setForm] = useState<Form>(blank()); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [refresh, setRefresh] = useState(0)
  const runnable = useMemo(() => (factors || []).filter(item => item.runnable), [factors]); const firstFactor = runnable[0]?.id || ''
  useEffect(() => { const c = new AbortController(); setError(''); Promise.all([fetchVisualStrategyDrafts(c.signal), fetchAssetPoolDrafts(c.signal), fetchFactorCatalogue(c.signal)]).then(([nextDrafts, nextPools, catalogue]) => { setDrafts(nextDrafts); setPools(nextPools); setFactors(catalogue.items); if (!editing) setForm(blank(catalogue.items.find(item => item.runnable)?.id || '')) }).catch(reason => { if (!c.signal.aborted) setError(reason instanceof Error ? reason.message : '无法读取可视化策略构建器') }); return () => c.abort() }, [refresh])
  const newDraft = () => { setEditing(null); setHistory(null); setForm(blank(firstFactor)); setError('') }
  const edit = async (draft: VisualStrategyDraft) => { setEditing(draft); setForm(fromDraft(draft)); setError(''); try { setHistory(await fetchVisualStrategyDraftHistory(draft.id, new AbortController().signal)) } catch (reason) { setError(reason instanceof Error ? reason.message : '无法读取历史') } }
  const selectPool = (value: string) => { const pool = pools?.find(item => item.id === value); if (pool) setForm(current => ({ ...current, poolId: pool.id, poolVersion: pool.version })) }
  const changeRule = (index: number, field: keyof VisualSignalRule, value: string) => setForm(current => ({ ...current, rules: current.rules.map((rule, i) => i === index ? { ...rule, [field]: field === 'threshold' ? Number(value) : value } as VisualSignalRule : rule) }))
  const addRule = () => setForm(current => current.rules.length >= 10 || !firstFactor ? current : ({ ...current, rules: [...current.rules, { factor_id: firstFactor, operator: 'gt', threshold: 0, direction: 'long' }] }))
  const save = async () => { if (saving) return; setSaving(true); setError(''); try { const allocation = form.mode === 'equal_weight' ? { mode: form.mode } : { mode: form.mode, target_weight: Number(form.targetWeight) }; const definition: VisualStrategyDefinition = { asset_pool: { asset_pool_draft_id: form.poolId, asset_pool_version: form.poolVersion }, signal_rules: form.rules, combination: form.combination, rebalance_frequency: form.frequency, allocation, constraints: { max_position_weight: Number(form.maxPositionWeight), max_holdings: Number(form.maxHoldings) } }; const result = await saveVisualStrategyDraft({ name: form.name, ...definition }, editing?.id); setEditing(result); setForm(fromDraft(result)); setHistory(await fetchVisualStrategyDraftHistory(result.id, new AbortController().signal)); setRefresh(value => value + 1) } catch (reason) { setError(reason instanceof Error ? reason.message : '保存失败') } finally { setSaving(false) } }
  if (error && (!drafts || !pools || !factors)) return <section className="empty-state wide"><AlertCircle size={24}/><strong>策略构建器暂不可用</strong><p>{error}</p><button className="detail-action" onClick={() => setRefresh(value => value + 1)}>重新读取</button></section>
  if (!drafts || !pools || !factors) return <section className="empty-state wide"><LoaderCircle size={24} className="animate-spin"/><strong>正在读取策略配置</strong><p>仅载入资产池版本、可运行因子和保存的定义；不会读取行情或计算信号。</p></section>
  const preservedPool = editing && !pools.some(item => item.id === form.poolId && item.version === form.poolVersion)
  return <div className="visual-strategy-workspace"><section className="page-heading"><div><p className="eyebrow">策略中心 · 可视化定义</p><h1>可视化策略构建器</h1><p>串联固定资产池版本、可运行因子和受限选股规则，保存为可审核的不可执行策略定义。</p></div><span className="static-boundary">定义 · 不可执行</span></section>
    {error && <div className="strategy-error"><AlertCircle size={17}/>{error}</div>}
    <section className="strategy-boundary"><ShieldAlert size={18}/><div><strong>策略内约束不等于全局风控</strong><p>此处仅保存选股、仓位与持仓数量约束。账户级敞口、杠杆、亏损和停单规则由“风控中心 → 风控规则”单独管理。不会运行因子、回测、生成收益、信号或订单。</p></div></section>
    <div className="visual-strategy-grid"><aside className="visual-strategy-drafts"><header><strong>可视化策略</strong><button onClick={newDraft}><Plus size={14}/>新建</button></header>{drafts.length ? drafts.map(item => <button key={item.id} className={editing?.id === item.id ? 'is-active' : ''} onClick={() => edit(item)}><span><strong>{item.name}</strong><small>{item.definition.signal_rules.length} 条规则 · v{item.version}</small></span><PencilLine size={14}/></button>) : <div className="strategy-empty"><Plus size={18}/><strong>还没有策略定义</strong><p>选择资产池和因子规则，保存即可创建第一版。</p></div>}</aside>
      <section className="visual-strategy-editor"><header><div><h2>{editing ? `编辑 ${editing.name} · 保存为 v${editing.version + 1}` : '新建策略定义'}</h2><p>引用只保存 ID 与版本，不复制资产池成员或因子公式。</p></div></header>
        <div className="visual-form"><label>策略名称<input value={form.name} maxLength={120} onChange={e => setForm(current => ({ ...current, name: e.target.value }))} placeholder="例如：月度动量候选"/></label><label>资产池固定版本<select value={form.poolId} onChange={e => selectPool(e.target.value)}><option value="">选择已保存资产池</option>{preservedPool && <option value={form.poolId}>保留引用 · {form.poolId.slice(0, 8)} · v{form.poolVersion}</option>}{pools.map(pool => <option key={pool.id} value={pool.id}>{pool.name} · 当前 v{pool.version} · {pool.instrument_count} 标的</option>)}</select><small>后续资产池更新不会修改此策略版本。</small></label><label>规则组合<select value={form.combination} onChange={e => setForm(current => ({ ...current, combination: e.target.value as Form['combination'] }))}><option value="all">全部规则均满足</option><option value="any">任一规则满足</option></select></label><label>调仓周期<select value={form.frequency} onChange={e => setForm(current => ({ ...current, frequency: e.target.value as Form['frequency'] }))}><option value="daily">每日</option><option value="weekly">每周</option><option value="monthly">每月</option></select></label></div>
        <section className="signal-rules"><header><div><strong>因子信号规则</strong><small>1–10 条；仅可选择目录中当前可运行的因子。</small></div><button type="button" disabled={form.rules.length >= 10 || !runnable.length} onClick={addRule}><Plus size={14}/>添加规则</button></header>{form.rules.map((rule, index) => <div className="signal-rule" key={`${index}-${rule.factor_id}`}><select value={rule.factor_id} onChange={e => changeRule(index, 'factor_id', e.target.value)}>{runnable.map(factor => <option key={factor.id} value={factor.id}>{factor.name} · {factor.id}</option>)}</select><select value={rule.operator} onChange={e => changeRule(index, 'operator', e.target.value)}><option value="gt">大于 &gt;</option><option value="gte">大于等于 ≥</option><option value="lt">小于 &lt;</option><option value="lte">小于等于 ≤</option></select><input aria-label="规则阈值" type="number" value={rule.threshold} onChange={e => changeRule(index, 'threshold', e.target.value)}/><select value={rule.direction} onChange={e => changeRule(index, 'direction', e.target.value)}><option value="long">纳入做多候选</option><option value="exclude">排除候选</option></select><button type="button" aria-label="删除规则" disabled={form.rules.length === 1} onClick={() => setForm(current => ({ ...current, rules: current.rules.filter((_, i) => i !== index) }))}><Trash2 size={15}/></button></div>)}</section>
        <div className="visual-form"><label>目标仓位方式<select value={form.mode} onChange={e => setForm(current => ({ ...current, mode: e.target.value as Form['mode'] }))}><option value="equal_weight">等权</option><option value="fixed_weight">固定目标权重</option></select></label>{form.mode === 'fixed_weight' && <label>固定目标权重<input type="number" min="0" max="1" step="0.01" value={form.targetWeight} onChange={e => setForm(current => ({ ...current, targetWeight: e.target.value }))}/><small>0–1，且不得高于单标的目标权重上限。</small></label>}<label>单标的目标权重上限<input type="number" min="0" max="1" step="0.01" value={form.maxPositionWeight} onChange={e => setForm(current => ({ ...current, maxPositionWeight: e.target.value }))}/><small>策略内约束，不是账户级风险限额。</small></label><label>最大持仓数<input type="number" min="1" max="200" step="1" value={form.maxHoldings} onChange={e => setForm(current => ({ ...current, maxHoldings: e.target.value }))}/></label></div>
        <button className="strategy-save" disabled={saving || !pools.length || !runnable.length} onClick={save}>{saving ? <LoaderCircle className="animate-spin" size={16}/> : <Save size={16}/>}{editing ? '保存策略新版本' : '保存策略定义'}</button>
      </section></div>
    {history && <section className="strategy-history"><header><div><History size={17}/><strong>{editing?.name} 的策略历史</strong></div><span>{history.length} 个版本</span></header>{history.map(item => <div key={item.id}><strong>v{item.version}</strong><span>{item.definition.asset_pool.asset_pool_draft_id.slice(0, 8)} · 资产池 v{item.definition.asset_pool.asset_pool_version} · {item.definition.signal_rules.length} 条规则 · {item.definition.rebalance_frequency}</span><time>{new Date(item.created_at).toLocaleString()}</time></div>)}</section>}
  </div>
}
